jcrist/msgspec

- msgspec/__init__.py
- msgspec/core.c
- tests/test_msgspec.py
Adds top-level `msgspec.encode`/`msgspec.decode` functions. These are slightly less efficient than their class-based counterparts, but for many use cases this difference should be negligible.
Fixes #3.
> Add top-level `encode`/`decode` functions

- docs/source/api.rst
- docs/source/index.rst
- msgspec/__init__.py
- msgspec/core.c
- msgspec/core.pyi
- tests/mypy_examples.py
- tests/test_msgspec.py
- tests/test_mypy.py
This adds support for both encoding and decoding [msgpack extension types](https://github.com/msgpack/msgpack/blob/master/spec.md#ext-format-family). This comes with 2 additional apis:
- A new `msgspec.Ext` type, representing the tuple of `(code: int, data: bytes_like)` that describes a msgpack extension.
- A new `ext_hook` parameter to `msgspec.Decoder`/`msgspec.decode`.
By default msgspec will deserialize all extension objects into `msgspec.Ext` objects. However, if a user specifies a `ext_hook` to `msgspec.Decoder`/`msgspec.decode`, this callback will be used instead to deserialize the extension type. Together with the existing `default` hook in `msgspec.Encoder`/`msgspec.encode`, this lets users fully add extra types to be serialized/deserialized.
For example, say we wanted to define …
> Add Extension Type support

- msgspec/core.c
- msgspec/core.pyi
- tests/mypy_examples.py
- tests/test_msgspec.py
Adds a new `dec_hook` callback supporting type conversions between
builtin msgpack types and arbitrary python types. This hook should have
the following signature:
```python
def dec_hook(obj: Any, type: Type) -> Any:
...
```
This receives an object composed of builtin msgpack types (e.g. dict,
list, int, ...) and the expected decode type (as described by the
decoder's type parameter). It should attempt to convert the value to the
provided type, or raise a type error appropriately. When combined with
`enc_hook` on the encoder, this lets users serialize arbitrary custom
objects without resorting to extension types.
For example, to serialize/deserialize a `NamedTuple` you might write
the following:
```python
import msgspec
from typing import NamedTuple
class Point(NamedTuple):
x: int
y: int …
```
> Add `dec_hook` to `Decoder`/`decode`

- msgspec/core.c
- tests/test_msgspec.py
- Fixes a memory leak in `Struct` constructors if an error occurred
- Some hygiene around attribute access on Encoder objects
> A few fixups

- docs/source/index.rst
- msgspec/core.c
- msgspec/core.pyi
- tests/mypy_examples.py
- tests/test_msgspec.py
Adds support for encoding/decoding `datetime.datetime` objects as MessagePack timestamp extensions.
Fixes #1.
> Add datetime support

- msgspec/core.c
- tests/test_msgspec.py
This applies a few buffer-oriented optimizations to speedup encoding (by
up to a factor of ~2x).
- Move resizing of write buffer to a separate function, and inline
`mp_write`. This allows gcc to do a better job of optimizing small
memcpy operations with little code bloat.
- When returning a `bytes` object from `encode`, don't hit realloc to
shrink the buffer down to the exact output size. Instead, we just shrink
the view presented to Python. This requires a bit of mucking in the
internals of the bytes object, but nothing too onerous. Since the output
of `encode` will usually be immediately written to a socket/file and
then dropped, this shouldn't result in an increase in application memory
usage.
> Optimize buffer usage in `encode`/`encode_into`

- msgspec/core.c
- Switch to a growth factor of 2x instead of 1.5x. This results in
increased performance at the cost of mildly increased memory usage.
- Add a fastpath for encoding ascii strings (which are common).
> A few more optimizations

- msgspec/core.c
This adds a freelist for "small" struct objects (currently defined as
`1 <= nfields <= 10`). Structs are added to the freelist during
deallocation, up to a per-size cap (currently 2000). Structs can then be
allocated from the freelist (if non-empty), skipping the cost of a
malloc.
To prevent keeping old pages around, the freelist is cleared every major
GC collection. This is done by a hook added to the module `m_traverse`
(since modules should persist for the lifetime of the program, they'll
usually be in the largest generation).
During high load, this leads to a measurable (4-6%) performance
improvement on deserialization.
> Use a freelist for struct types

- msgspec/core.c
No need to dispatch on type when encoding a struct key, we already know
it's a string.
> Optimize struct key serialization

- msgspec/core.c
- tests/test_msgspec.py
Encodes floats in 30% the previous time, and decodes in 70% the previous
time.
> Improve float encode/decode performance

- benchmarks/bench.py
- docs/source/usage.rst
- msgspec/core.c
- tests/test_msgspec.py
This adds support for `Union` types (with a few restrictions). Specifically only one of each of the following types may appear within a single union:
- Array-like collections (tuple, list, ...)
- Map-like collections (dict, Struct, ...)
- IntEnum or int
- Enum or str
This has a mild (negligible) performance degradation for typed decoders, and a slightly larger performance degradation for untyped decoding. I think this is fine, as most users should use the typed decoders anyway, since `Struct` types in general make things much faster.
> Support `Union` types

- docs/source/usage.rst
- msgspec/core.c
- tests/test_msgspec.py
We support encoding memoryview objects as binary blobs, but don't support decoding into `memoryview` objects for typed decoders. We could add support pretty easily, but since:
- memoryviews are usually an optimization to avoid copying (and a copy is necessary on decode)
- mypy will accept passing a `memoryview` to a signature annotated `bytes` already, so encode-side annotations are fine.
I don't see decode support as being necessary now. For all uses decoding into a `bytes` or `bytearray` makes more sense IMO.
Fixes #52 (well, kind of. I don't think the original request there makes sense anymore).
> Support serializing memoryview objects

- msgspec/_core.c
Newer versions of visual studio don't define `ssize_t` (which we didn't
really need to be using here anyway). Swap for `Py_ssize_t` everywhere.
Also replace some stray `\t` that showed up somehow.
> Fix windows builds with new VS

- msgspec/_core.c
- tests/test_enum.py
This adds an optimized lookup for IntEnum types. For small/compact
ranges of values this uses a direct index with an offset. For larger
ranges (where a direct index would result in too much wasted space) a
simple hashmap is used. To avoid recreating the lookup table multiple
times, it's stored on the enum class itself as the `__msgspec_lookup__`
attribute.
This switches the decoding process from:
- Decode int64_t/uint64_t value
- Create python int from this value
- Get `IntEnum` class
- Lookup python int on `IntEnum` class
to
- Decode int64_t/uint64_t value
- Get lookup table (already stored in the decoder `TypeNode` tree)
- Lookup value in lookup table
On my machine this results in:
- ~12x improvement in decode speed for compact ranges (1, 2, 3, 4, ...)
of enums (as fast or faster than …
> Speedup decoding of IntEnums

- msgspec/_core.c
- tests/test_json.py
- tests/test_msgpack.py
I thought these already worked, but they didn't. Type unions using the
`int | None` syntax create a `types.UnionType` object, not a
`typing.Union` object. Unfortunately `types.UnionType` doesn't define
`__origin__` (like all other generic types do), so this wasn't being
properly handled by the previous logic. This PR fixes this and adds a
test for Python 3.10+.
> Support Python 3.10 type unions

- msgspec/_core.c
- tests/test_json.py
Previously this was restricted to `str` or `Any` types only, we now also
support string literal types. We could extend this to any type that
encodes as a string, but I'm reluctant to expand the API here unless
asked.
Fixes #76.
> Support string literal types as keys in JSON

- .github/workflows/ci.yml
Maybe this will fix the missing Python 3.10 wheel builds.
> Upgrade cibuildwheel

- msgspec/__init__.pyi
The `__struct_fields__` annotation should have been a `ClassVar`,
without that annotation the pyright `__dataclass_transform__`
interpreted it as a field, breaking things.
> Fix pyright type inference

- msgspec/_core.c
Looking up the module state is generally pretty quick, but if done in a
hot path (e.g. encoding/decoding when not raising an exception) it can
add up. We now store a reference to the module state on the encoder,
which reduces the cost of serializing `enum.Enum` objects by 20-30%, and
negligibly improves a few other encode paths. We also micro-optimize a
few other places where we access the module state. This could be done on
the decoder as well, but (almost) all access in the decoder is for
raising errors and so wouldn't improve performance in common hot paths.
> Reduce module state lookup in hot paths

- msgspec/_core.c
- tests/test_json.py
- tests/test_msgpack.py
For the common case of `msgspec.json.decode(msg, type=Struct)`, we can
allocate the `TypeNode` on the stack and have a faster init path,
reducing overhead per call. This still isn't as fast as creating a
`Decoder` once and using `Decoder.decode`, but it brings things closer.
On my machine, decoding a simple `Point(x=1, y=2)` struct takes the
following times:
- `decode` (master): 240 ns
- `decode` (this PR): 150 ns
- `Decoder.decode`: 120 ns
> Micro-optimize `decode(type=Struct)`

- msgspec/_core.c
- tests/test_json.py
- tests/test_msgpack.py
Between the original PR (#77) being made and merged a change went in that
broke the optimization (specifically, the type code for struct types was
split into `MS_TYPE_STRUCT` and `MS_TYPE_STRUCT_ARRAY`). This fixes the
bug, and expands the tests to provide a more localized check for this
behavior.
> Fixup decode(..., type=Struct) optimization

- benchmarks/bench_gc.py
- docs/source/benchmarks.rst
- docs/source/perf-tips.rst
- docs/source/structs.rst
- msgspec/_core.c
- tests/test_struct.py
- Previously GC tracking was disabled for structs with `nogc=True`, but kept the same GC-enabled memory layout. This PR changes nogc structs to truly be non-GC types. This reduces memory usage per instance by 16 bytes. It also lets `dict` and `tuple` instances containing `nogc=True` structs to also not be tracked instances, further reducing GC load.
- Further optimize the allocation code paths for structs. We now no longer needless track structs just to untrack them later, resulting in a micro speedup. We also optimize at import time `tp_setattr` and `tp_free`, rather than branching per-call.
- Add a benchmark for GC usage comparing structs, structs with nogc=True, classes, and classes with `__slots__`. This shows a major reduction in GC pause time for applications with a large number of …
> Improve nogc support

- msgspec/_core.c
- tests/test_struct.py
A frozen struct instance can be used directly as a default value without creating a copy.
> No need to copy frozen structs used as defaults

- docs/source/structs.rst
- msgspec/__init__.pyi
- msgspec/_core.c
- tests/basic_typing_examples.py
- tests/test_common.py
- tests/test_struct.py
Adds a `rename` option to a struct definition. This takes either a string describing a rename method (``"lower"``, ``"upper"``,
``"camel"``, or ``"pascal"`` for lowercase, UPPERCASE, camelCase, or PascalCase respectively), or a callable from str -> str that will be called on every field name. Renamed fields are used for encoding/decoding only, and are intended for cases where you need the JSON field names to be something different than what you wish to use in Python (a common case would be applying camelCase to encoded JSON, but using snake_case in python).
Example:
```python
In [1]: import msgspec
In [2]: class Example(msgspec.Struct, rename="camel"):
...:     field_one: int
...:     field_two: str
...: 
In [3]: ex = Example(1, field_two="two")  # in python code the field names are the …
```
> Add support for renaming fields

- docs/source/api.rst
- docs/source/structs.rst
- msgspec/__init__.py
- msgspec/__init__.pyi
- msgspec/_core.c
- tests/basic_typing_examples.py
- tests/test_mypy.py
- tests/test_struct.py
Adds a method for dynamically defining new struct types. This is helpful
for situations where types aren't known until runtime, but you still
want to provide type validation when encoding/decoding.
> Add `defstruct`

- .github/workflows/ci.yml
- msgspec/_core.c
- tests/test_msgpack.py
This resolves #103 by adding steps for Linux and Mac ARM wheels in the CI build. I also bumped the version of pypa/cibuildwheel to v2.4.0.
Mac support: https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon
Linux support: https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation
I don't have a great way of testing this. :smile:
> Adding Linux and Mac ARM wheels

- .github/workflows/ci.yml
While we publish a large number of pre-built wheels, we don't need to
build and test all of them for every PR. This PR reduces the non-release
builds to:
- Completely skip musllinux
- Skip aarch64 except for cpython 3.10
Follow-up from #104.
> Speedup Linux CI

- .github/workflows/ci.yml
- msgspec/_core.c
- setup.cfg
- setup.py
- tests/test_mypy.py
- tests/test_pyright.py
- Add `asan`/`ubsan` build & tests to CI
- Fixes bugs found when running with `asan`/`ubsan`, as well as silencing some warnings found by running clang's static analysis locally.
> Use `asan` and `ubsan` in CI

- docs/source/usage.rst
- msgspec/_core.c
- tests/test_msgpack.py
- Fix memory leak for messages with trailing characters
- Properly forward error for malformed msgpack submessages
- Fix typo in bytes docs
- Fix memory leak when decoding invalid set
- Fix msgpack decode invalid opcode error message
> A few small fixups

- msgspec/_core.c
A refcounting error here was leading to a leaking tuple reference,
causing memory to grow over time. This fixes the issue, verified with
`memray` output. No test added yet, as testing for memory leaks will
require some more work.
Fixes #114.
> Fix memory leak in Struct.__reduce__

- benchmarks/bench.py
- msgspec/_core.c
- tests/test_json.py
This significantly speeds up JSON string decoding. Using some ideas borrowed from yyjson, as well as some general performance tricks, we:
- Use a new lookup table for determining interesting char values that require special handling.
- Have separate processing loops for ascii and unicode
- Split off the (less common) escape handling routine into a separate function.
- Manually unroll the string processing loops
- Apply an inline asm hack to get GCC to generate better code
Besides a faster string parsing inner loop, this also lets us determine if a string is all ascii characters for free. In this case, we skip calling `PyUnicode_DecodeUTF8` and instead manually create the new string object, further accelerating decoding.
In general, this results in:
- 2x speedup for decoding ascii-only …
> Faster json string parsing

- msgspec/_core.c
- tests/test_json.py
This further optimizes the decoding of Struct types by rearranging the
field lookup loop a bit to avoid `%` operations. This optimization
is most effective on gcc, resulting in a 20% speedup in decode time.
Clang already did most of this optimization automatically. With this
change, on gcc `bench.py` decreases from ~700 us to ~550 us for json
decoding.
> Speedup struct decoding

- msgspec/_core.c
- tests/test_json.py
This adds a cache for ascii string dict keys for the JSON decoder only.
Since most JSON objects are structured (with repeated keys), this helps
improve performance by reusing the same string key objects multiple
times. This slightly reduces performance for cases where string keys
don't repeat (cache is overhead only), but can result in up to 40%
speedup in cases where the cache is hit. Using a cached string:
- Removes the cost of string validation and allocation
- Reduces memory usage by reusing objects
- Removes the need for a siphash24 call, since string hashes are cached
on the string object itself.
The cache is cleared currently every 10 major GC passes to periodically
free up old pages and reduce fragmentation.
> Add cache for short JSON ascii dict keys

- msgspec/_core.c
- tests/test_json.py
- tests/test_msgpack.py
Previously we added a cache for short ascii string keys when decoding
dicts using JSON. We now expand this optimization to the msgpack decoder
as well.
> Use dict str cache for msgpack decoder

- benchmarks/bench.py
- benchmarks/bench_gc.py
- docs/source/benchmarks.rst
- docs/source/perf-tips.rst
- docs/source/structs.rst
- msgspec/__init__.pyi
- msgspec/_core.c
- tests/basic_typing_examples.py
- tests/test_json.py
- tests/test_msgpack.py
- tests/test_struct.py
All other option names are `_` separated, so this should really be
`no_gc`. The double-negative feels unnecessary, it's cleaner just to
name this `gc`, defaulting to `gc=True`.
This is a breaking change, but afaik no one is really using this option
right now so a breaking change feels fine.
> Rename `nogc` to `gc`

- setup.py
The `include_package_data=True` flag was set (I think this was a
copy-paste from an example for distributing `.pyi` files in the
package). This option automatically includes all files in the source
tree in the built wheel as package data (including the original C
source). Since we alreay manually set `package_data`, the boolean flag
is unnecessary, and the C source adds a (comparatively) non-negligible
amount of data to the the built `whl`. No need to set this flag, and
removing it decreases the package size.
> Don't accidentally include C source in built whl

- msgspec/__init__.pyi
- msgspec/_core.c
- tests/basic_typing_examples.py
- tests/test_struct.py
This adds a new `weakref` config option for structs. If `True`, instances of the struct type will support weakrefs. Defaults to False.
This was requested by a user for quickle (https://github.com/jcrist/quickle/issues/63), which isn't actively maintained, but is the predecessor for `msgspec`. It was easy enough to add, and uncovered a few subtle bugs (fixed here):
- Fixes a bug when deallocating long chains of Struct instances, which requires trashcan support. Previously the freelist interactions were done outside of the TRASHCAN macros, which was incorrect.
- Fixes a bug where `Struct` types with a `__del__` method and GC support interacted poorly with the freelist, potentially causing reused instances to fail to run their `__del__` method.
> Add `weakref` support to Struct types

- docs/source/structs.rst
- docs/source/usage.rst
- msgspec/__init__.pyi
- msgspec/_core.c
- tests/basic_typing_examples.py
- tests/test_common.py
- tests/test_json.py
- tests/test_msgpack.py
- tests/test_struct.py
Previously tagged unions only supported `str` tag values. We now also
support `int` tag values, with a few caveats:
- A single `Union` of `Struct` types cannot mix both `int` and `str` tag
types.
- Integer `tag` values currently only support values that fit in an
int64 (``-2**63 <= tag <= 2**63 - 1``). This restriction has also been added
to `IntEnum` and integer `Literal` types (previously these supported up
to a `uint64`). This restriction makes the implementation easier, but
can be removed if needed in the future. For now a `NotImplementedError`
is raised if the user attempts to use out-of-range integer values,
pointing them to raise an issue on GitHub if they need the feature.
Fixes #134.
> Support integer Struct tags

- msgspec/_core.c
- tests/test_struct.py
`__init_subclass__` runs halfway through a type being defined.
Previously this meant that if a user defines a `Struct` subclass with an
`__init_subclass__` hook, that hook gets called before the `Struct` type
is fully defined, meaning that if the user trys to do any struct
operations with that class inside `__init_subclass__` a segfault could
occur.
Rather than splitting our struct definition routine into two parts
(with the second part running in a base `__init_subclass__` that any
users overriding `__init_subclass__` would need to remember to call), we
instead forbid struct operations on half-defined types. This shouldn't
cause any real issues for users, but prevents a possible segfault during
naive usage.
Fixes #73.
> Forbid struct operations in `__init_subclass__`

- docs/source/usage.rst
Hoping to clarify the confusion raised in https://github.com/jcrist/msgspec/issues/134#issuecomment-1175654039.
> Clarify field order in `array_like=True` structs

- msgspec/_core.c
This adds some naive linting tests for easy to detect errors when using
the cpython capi. It also fixes some bugs exposed by these tests:
- Adds a test that every successful call to `Py_EnterRecursiveRepr`
doesn't return without calling `Py_LeaveRecursiveCall`
- Adds a test that every successful call to `Py_ReprEnter` doesn't
return without calling `Py_ReprLeave`
> Add some naive cpython api linters

- docs/source/usage.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_json.py
- tests/test_msgpack.py
- Adds support for encoding subclasses of tuples
- Adds support decoding into `typing.NamedTuple`/`collections.namedtuple` types
Fixes #158.
> Support namedtuples

- docs/source/usage.rst
- msgspec/_core.c
- tests/test_json.py
- tests/test_msgpack.py
Previously timezone-naive datetime objects would always error during
encoding. We now support encoding these through a custom ``enc_hook``
(the default is still to error). I _think_ this makes sense, but it's a
little weird since at the type level this means that only some
`datetime` objects will hit the `enc_hook`. If only python had two
different classes for representing timezone-aware and timezone-naive
datetimes.
Fixes #152.
> Support timezone-naive datetimes with enc_hook

- msgspec/_core.c
- tests/test_common.py
- tests/test_json.py
- tests/test_msgpack.py
- tests/test_struct.py
This adds test coverage in `_core.c` for all missing (but testable)
lines, down to ~line 7000 (another pass will be needed to get the rest).
It also fixes a few bugs that turned up due to missing testing, mostly
around error propagation when raising nice errors for JSON-invalid
types. None of the bugs fixed here would have resulted in runtime
issues, just worse error messages.
> Increase _core.c coverage

- msgspec/_core.c
This fixes a small bug in the error handling for `TypeNode` creation for
`TypedDict`/`NamedTuple` types. The logic for creating these types goes:
- Create a new node
- Cache it on the object (the typeddict/namedtuple object itself)
- Populate the node
In the case of an error during the last step, an attempt is made to
delete the node from the object (since the type is invalid). Previously,
if an error occurred during `PyObject_DelAttr`, we'd clear the error and
continue. This would accidentally lead to no error being returned,
causing a `SystemError` later on.
This was definitely a bug, but I'm not sure why that delattr call would
fail here. I'm seeing a few rare flaky test failures that could have
been caused by this faulty logic, but I'm unable to reproduce the
failures locally. Pushing …
> Fixup TypedDict/NamedTuple error handling branch

- .codecov.yml
This has been a false failure more often than it has been useful (not
sure why). Since I mostly want coverage for introspection not for actual
CI checks, I'm disabling this for now.
> Disable codecov patch status

- msgspec/__init__.pyi
- msgspec/_core.c
- tests/basic_typing_examples.py
- tests/test_struct.py
Hi,
this should implement builtin renaming to kebap-case.  I didn't test the code due to me virtually never working with Python and less with its C API, so it'd be good if someone else tested it.  Also, I only added one test case where I saw fit/understood the testing harness, more could be added but I wouldn't know how.
> [UNTESTED] Add support for renaming to kebap-case

- docs/source/api.rst
- docs/source/index.rst
- docs/source/jsonschema.rst
- msgspec/_core.c
- msgspec/_utils.py
- msgspec/json.py
- msgspec/json.pyi
- tests/basic_typing_examples.py
- tests/test_schema.py
This adds two functions:
- ``msgspec.json.schema`` for generating a single JSON Schema from a
given type.
- ``msgspec.json.schema_components`` for generating multiple schemas
(and a corresponding components mapping) from multiple types.
~Still needs docs and tests.~
Fixes #125.
> Generate JSON Schemas from types

- msgspec/_core.c
- tests/test_constraints.py
Fixes a bug in the error handling code of `Meta.__repr__`. Also simplifies the internal `strbuilder` utility to remove a potential footgun caused by an optimization with dubious benefit.
> Fix a bug in `Meta.__repr__`

- docs/source/structs.rst
- msgspec/__init__.pyi
- msgspec/_core.c
- tests/basic_typing_examples.py
- tests/test_struct.py
This adds support for passing either a `Mapping[str, str]` or a callable of signature `Callable[[str], Optional[str]]` (the `Optional` is the new bit) to `rename`. This makes it easier to only rename a few fields in a struct, as the rename function doesn't need to handle every field.
Simplifies the use case described in #182.
> Support mappings for `rename`

- msgspec/__init__.pyi
- tests/basic_typing_examples.py
`__match_args__` has long been supported for struct types, but the type hint in the corresponding `.pyi` file was missing, causing mypy/pyright to complain when using match-case statements on struct types.
> Add missing type hint for __match_args__

- msgspec/json.pyi
- msgspec/msgpack.pyi
- tests/basic_typing_examples.py
Currently mypy doesn't interpret things other than classes as being compatible with `Type[T]` (they literally have to be instances of `type`). This makes it hard to properly type the `decode` methods or `Decoder` constructors, as passing type-like-things (e.g. `Union[int, str]`) will error under mypy. `pyright` doesn't have this limitation.
For now we add a fallback `overload` to these methods that infers the decoder type as `Decoder[Any]`. This means that `mypy` will no longer error, but will require an explicit annotation to infer the type of the output of `decode`.
If/once the `TypeForm` PEP lands, this hack can be removed. Until then `pyright` support for these annotations will be much better than `mypy` support.
Fixes #173.
> Work around mypy limitations

- docs/source/examples/conda-repodata.rst
- docs/source/examples/index.rst
- docs/source/perf-tips.rst
- examples/conda-repodata/query_repodata.py
This example benchmarks a few different JSON libraries, and compares using them to parse and query the `current_repodata.json` file from conda-forge. It's a good example of using `Struct` types to define smaller "views" of the data only including the needed fields for an operation. This reduces allocations, significantly increasing performance.
> Add conda-repodata example

- .github/workflows/ci.yml
- setup.py
Updates CI and build script to build 3.11 release builds rather than using the 3.11 pre-releases.
> enable 3.11 builds

- docs/source/usage.rst
- msgspec/_core.c
- msgspec/_utils.py
- tests/test_common.py
- tests/test_json.py
- tests/test_msgpack.py
- tests/test_schema.py
Previously integer enums encoded/decoded by their integer *values*,
while all other enums encoded/decoded by their string *names*. This PR
changes things so that all enums encode/decode by their values (string
and integer values only supported for now).
**This is a breaking change**
Before this PR:
```python
import enum
import msgspec
class Example(enum.Enum):
A = "x"
msgspec.json.encode(Example.A)
```
After this PR:
```python
import enum
import msgspec
class Example(enum.Enum):
A = "x"
msgspec.json.encode(Example.A)
```
Many other tools in the python ecosystem support encoding enums as their
values by default (`orjson`, `pydantic`, `cattrs`, `json`), but no tool
AFAICT supports encoding as their names by default. The purpose of this
change is to better match the rest of the Python …
> breaking: Encode/decode all enums by value.

- msgspec/_core.c
The string `"value"` is no longer used after #211, no need to intern it anymore.
> Remove unused interned string

- msgspec/_utils.py
- tests/test_schema.py
When `forbid_unknown_fields` was added to the `Struct` configuration, I forgot to update the `msgspec.json.schema` functions to augment the generated schemas with this configuration. This PR fixes that.
> Support `forbid_unknown_fields` in json-schema generation

- .github/workflows/ci.yml
- msgspec/_core.c
The tests that a JSON incompatible `NamedTuple`/`TypedDict` would raise a nice error message previously would sometimes fail with a `SystemError` indicating a `NULL` return value without a valid exception. This was tricky to track down due to how rare the failure was (~1/500 runs).
The issue turns out to be that `PyObject_DelAttr` may sometimes clear an existing exception, even if no new exception is raised. Why this happens isn't clear to me; it may be a bug in CPython, or expected behavior.
To fix this, we now use `PyErr_Fetch`/`PyErr_Restore` to ensure the proper exception persists through the `PyObject_DelAttr` calls.
> Fix flaky NamedTuple/TypedDict tests

- msgspec/_core.c
- tests/conftest.py
- tests/test_common.py
- tests/test_json.py
Previously there was a bug in the base64 encoding implementation used by `msgspec.json` for encoding `bytes`/`bytearray`/`memoryview` objects. This bug only appeared for bytes with values outside the range 0 <= x <= 127, which weren't caught by the existing tests.
To remedy this we:
- fix the bug
- augment the existing test suite to cover this situation
- add some fuzz testing for the base64 encoding code
Fixes #215.
> Fix bug in JSON base64 encoding

- docs/source/usage.rst
- msgspec/_core.c
- msgspec/_utils.py
- tests/test_common.py
- tests/test_schema.py
- tests/utils.py
This PR adds encoding/decoding support for dataclasses, mirroring our support for `typing.NamedTuple`/`collections.namedtuple`/`typing.TypedDict`. Dataclasses are encoded to/decoded from mappings containing all attributes assigned to the object (union of `__dict__` and `__slots__`).
I do not intend to add support for additional configuration (e.g. renaming fields using `camelCase`) - if the user wants more customization they should switch to using structs. Structs support all the common features of dataclasses, but are more performant to create/use/encode/decode, and are more customizable. The intent of adding dataclass support is:
- Compatibility with what `orjson` is capable of encoding efficiently. Initial benchmarks show the implementation here encodes measurably faster than the one …
> dataclass support

- docs/source/usage.rst
- msgspec/_core.c
- msgspec/_utils.py
- tests/test_common.py
- tests/test_json.py
- tests/test_schema.py
These are encoded as RFC3339 formatted strings.
Part of #220.
> Add support for encoding/decoding `datetime.date` objects

- docs/source/usage.rst
- msgspec/_core.c
- msgspec/_utils.py
- tests/test_common.py
- tests/test_schema.py
This adds support for encoding/decoding UUIDs as strings in the format described by RFC4122.
The encoding and decoding are done as efficiently as possible - on my machine UUIDs
- encode ~2x faster than orjson
- encode ~70x faster than pydantic
- decode ~10x faster than pydantic
Benchmark:
```python
In [1]: import msgspec, orjson, pydantic, uuid
In [2]: class Struct(msgspec.Struct):
...:     data: list[uuid.UUID]
...: 
In [3]: class Model(pydantic.BaseModel):
...:     data: list[uuid.UUID]
...: 
In [4]: data = [uuid.uuid4() for _ in range(5000)]
In [5]: struct = Struct(data=data)
In [6]: model = Model(data=data)
In [7]: enc = msgspec.json.Encoder()
In [8]: dec = msgspec.json.Decoder(Struct)
In [9]: msg = enc.encode(struct)
In [10]: %timeit enc.encode(struct)  # msgspec encode time
252 µs ± …
```
> Add support for encoding/decoding UUIDs

- docs/source/constraints.rst
- docs/source/usage.rst
- msgspec/__init__.pyi
- msgspec/_core.c
- msgspec/_utils.py
- tests/basic_typing_examples.py
- tests/test_constraints.py
- tests/test_json.py
- tests/test_msgpack.py
- tests/test_schema.py
This PR addresses part of #220. It makes the following changes:
- Naive `datetime.datetime` objects are now encoded as ISO8601 compatible strings for all protocols. These are _almost_ RFC3339 compatible, but lack the timezone component.
- A `datetime.datetime` annotation now will decode both timezone-naive and timezone-aware `datetime.datetime` objects.
- A new `tz` constraint is added for configuring whether the annotated value is timezone-aware or timezone-naive (or both). Set to `True` to enforce timezone-aware and `False` to enforce timezone-naive. Defaults to `None`, which accepts both.
- The `msgpack` protocol now will also decode `datetime.datetime` objects from RFC3339/ISO8601 compatible strings. Previously it only accepted datetimes encoded using the msgpack timestamp extension.
> Support both timezone-aware and timezone-naive datetime objects

- docs/source/usage.rst
- msgspec/_core.c
- msgspec/_utils.py
- tests/test_common.py
- tests/test_constraints.py
- tests/test_schema.py
Final part of #220. Adds support for encoding and decoding `datetime.time` objects, following the same rules as `datetime.datetime` objects.
Fixes #220.
> Support encoding/decoding time objects

- docs/source/structs.rst
Noticed this small typo in the Struct documentation. The example appears to be valid now.
> Fix typo in docs for runtime definition of Struct

- docs/source/usage.rst
- msgspec/_core.c
- tests/test_common.py
Previously we encoded all attributes set on a dataclass object. Unfortunately the pydantic implementation of dataclasses hides some pydantic-specific stuff in private attributes set on the object. To avoid encoding these attributes, we now skip any attribute that starts with a leading `_`.
Fixes #233.
> Don't encode dataclass attributes with leading `_`

- msgspec/_core.c
- tests/test_json.py
Previously our check to ensure valid JSON types was too strict, preventing key constraints from being used. This has now been relaxed and a test added.
Fixes #238.
> Support dict key constraints in JSON

- docs/source/usage.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_json.py
JSON as a protocol only supports string keys in objects, which means that arbitrary key types can't be used. Previously we only allowed `str` and `Literal[strings...]` types for dict keys. This PR relaxes this restriction to also support int-like keys. The following key types are now supported for JSON:
- `str`
- `Literal[strings...]`
- `Enum`
- `int`
- `Literal[integers...]`
- `IntEnum`
along with constraints on these types.
Integer keys are encoded/decoded as integer strings (e.g. `1 -> "1"`). There is precedent for this change - the stdlib `json` library does this automatically for `int` keys, as does `orjson` (opt in with `OPT_NON_STR_KEYS`). Golang's `json` library and protobuf-json also does this for integer keys. The standard `citm_catalog.json` benchmark file also has a schema …
> Support encoding/decoding dict int keys for JSON

- msgspec/_utils.py
- tests/test_schema.py
When `kw_only` support was added for `Struct` types, I forgot to update the `msgspec.json.schema` method to properly handle `kw_only` fields. This PR fixes that, and adds tests to cover these cases.
> Fix jsonschema generation for kw_only structs

- docs/source/conf.py
- docs/source/usage.rst
- msgspec/_core.c
- tests/test_common.py
This adds support for encoding `set` and `frozenset` subclasses. These are added mostly for parity with `list`/`tuple`/`dict` types - with these additions all natively supported "collection" types also support subclasses.
This PR also adds a bit of clarification around our support of subclasses for natively supported types.
Fixes #248.
> Support encoding `set`/`frozenset` subclasses

- docs/source/usage.rst
- msgspec/_core.c
- msgspec/_utils.py
- tests/test_common.py
- tests/test_schema.py
`NewType` types are treated identically to their base types by msgspec. Support here is purely to aid with static type checking systems like mypy or pyright.
~Still needs docs, just putting this up since it's quick and easy to do.~
Fixes #250.
> Support NewType

- docs/Makefile
- msgspec/_core.c
The recent changes to `Raw` broke the docs build, which went unnoticed since warnings in the docs build were being silently ignored. This commit fixes the docs build, and also updates the sphinx config to make warnings result in a build failure.
> Fix docs build

- docs/source/api.rst
- msgspec/__init__.py
- msgspec/__init__.pyi
- msgspec/_core.c
- tests/basic_typing_examples.py
- tests/test_struct.py
This adds a new `msgspec.replace` function, mirroring the functionality of `dataclasses.replace`/`NamedTuple._replace`/`attrs.evolve`. It takes an existing `Struct` instance, and returns a copy with any fields passed as `**changes` replacing the original values.
Note that:
- This works on any struct (including frozen structs), since this returns a new instance rather than mutating the old instance.
- This doesn't do a deepcopy of any of the field values. If the input struct had a list on a field, the output struct will have the same instance of that list (unless that field was passed in `**changes`).
Fixes #261.
> Add `msgspec.replace` function

- .github/workflows/ci.yml
- docs/source/api.rst
- msgspec/__init__.py
- msgspec/__init__.pyi
- msgspec/toml.py
- setup.py
- tests/basic_typing_examples.py
- tests/test_toml.py
This adds TOML support in a new `msgspec.toml` module. This uses:
- `tomli` (or `tomllib` for Python 3.11+) for decoding
- `tomli_w` for encoding
Both are optional dependencies that may be installed using the new
`toml` extra.
As with YAML support, only `encode`/`decode` methods are supported for
now, no `Encoder`/`Decoder` classes.
> Add TOML support

- docs/source/examples/index.rst
- docs/source/examples/pyproject-toml.rst
- examples/pyproject-toml/pyproject.py
This adds a new example showing parsing a `pyproject.toml` file into a type-checked object using `msgspec`.
> Add pyproject.toml example

- msgspec/_core.c
- msgspec/inspect.py
- tests/conftest.py
- tests/test_common.py
- tests/test_inspect.py
> Support arbitrarily nested `NewType`/ `Annotated` types

- msgspec/_core.c
- tests/test_struct.py
We now include the name of the first invalid keyword argument, which should make it easier to debug keyword arg typos.
This request came as feedback over email:
> when providing an incorrect kwarg, it would be great if the error message could tell you which kwarg was incorrect, e.g. right now its just 'Extra keyword arguments provided'.
> Improve error for invalid kwarg in `Struct.__init__`

- docs/source/api.rst
- docs/source/structs.rst
- examples/pyproject-toml/pyproject.py
- msgspec/__init__.py
- msgspec/__init__.pyi
- msgspec/_core.c
- msgspec/_json_schema.py
- msgspec/inspect.py
- tests/basic_typing_examples.py
- tests/test_common.py
- tests/test_inspect.py
- tests/test_struct.py
This PR does a few things:
- It adds a new `msgspec.field` function, which returns an *opaque* object used for configuring fields. So far this only exposes `default` and `default_factory`, both of which match the `dataclasses` kwargs of the same name.
- It adds support for init-time generated default values in `msgspec.Struct` types, through use of the new `default_factory` setting (fixes #259).
Example:
```python
import msgspec
import uuid
class Example(msgspec.Struct):
id: uuid.UUID = msgspec.field(default_factory=uuid.uuid4)
```
This also changes how mutable default values are handled. Previously msgspec's semantics were that a default value for a field would be deepcopied on `__init__` if that field wasn't provided (the implementation would avoid a deepcopy for most common types, but …
> Add support for `default_factory` on `Struct` types

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature.yml
Manually fix whitespace/newline issues in the markdown, since the markdown renderer here doesn't seem to handle whitespace the same way github's markdown renderer does elsewhere.
> Fixup issue templates

- docs/source/structs.rst
- msgspec/_core.c
- tests/test_struct.py
Previously this was unsupported.
Postponed annotation evaluations are a bit of a tricky issue here. We currently don't parse type annotations at import time (we do so lazily on the first decode call). This is nice for two reasons:
- It keeps import times quick. Especially for CLI applications where not all struct types will be decoded in a single invocation, it pays off to avoid parsing types unless needed.
- It plays better with recursive structures, since we won't ever parse a type that isn't fully defined.
However, we do need to know which attributes are/aren't fields at Struct type definition time, which means we'll have to detect if an attribute is a `ClassVar` *without* eval-ing the annotation string. This is a bit tricky to get right (enough), without compromising on performance. …
> Support ClassVar on Struct types

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_json.py
Support JSON encoding and decoding any str-like or int-like dict key
Previously the JSON encoder/decoder only supported dicts with `str` or `int` keys. We now support using any type that maps to an `int` or `str` as a dict key.
> Json extended dict key types

- benchmarks/bench_validation.py
- docs/source/benchmarks.rst
Drops `marshmallow` in favor of `mashumaro` for the validation benchmark. Unlike `marshmallow`, `mashumaro` actually makes performance claims. We drop `marshmallow` instead of just adding a new grouping to make better use of the y-axis since there's not the marshmallow outlier taking up half the space.
> Add mashumaro benchmark

- msgspec/_core.c
- tests/test_json.py
This bug resulted in a memory leak when decoding JSON into Struct types. This issue was introduced in 0.13.0 due to a misplaced INCREF.
This PR fixes the issue, and adds a test to prevent a regression.
Fixes #311.
> Fix refcount bug in json decoding of Struct types

- docs/source/api.rst
- docs/source/conf.py
- msgspec/__init__.pyi
- msgspec/_core.c
- msgspec/inspect.py
- msgspec/structs.py
- msgspec/structs.pyi
- tests/basic_typing_examples.py
- tests/test_struct.py
This adds a new `__struct_config__` attribute to struct classes and instances. This attribute holds a (dynamically created) `msgspec.structs.StructConfig` instance describing the configuration settings for the respective struct type. Note that these settings are immutable; this object is only useful for type introspection, not for modifying settings of existing types.
Previously these settings were exposed through private (and undocumented) attributes. Those attributes have all been removed in favor of this new public interface.
```python
class Point(msgspec.Struct, frozen=True):
x: int
y: int
assert Point.__struct_config__.frozen
```
Fixes #327.
> Add `Struct.__struct_config__` attribute

- docs/source/api.rst
- msgspec/structs.py
- msgspec/structs.pyi
- setup.cfg
- tests/basic_typing_examples.py
- tests/test_struct.py
This mirrors the functionality in `dataclasses.fields`, returning a tuple of `FieldInfo` objects providing information about the individual struct fields.
Supersedes #282.
> Add `msgspec.structs.fields` utility

- msgspec/__init__.pyi
- msgspec/_core.c
- msgspec/structs.pyi
- tests/basic_typing_examples.py
- tests/test_struct.py
This adds a new `dict` option on a `Struct` type, disabled by default. Enabling this will add a lazily-allocated `__dict__` attribute to all instances of that type, which can be used to store additional runtime state. Note that any data stored in the `__dict__` is _not_ encoded/decoded/pickled/copied by default.
One use of this is to support `functools.cached_property` on `Struct` instances, since this decorator stores the cached value on the instance `__dict__`.
Fixes #324, fixes #204.
> Add option to define `__dict__` on `Struct` type

- msgspec/_core.c
- tests/test_constraints.py
There was a bug in the handling of integer `lt` constraints that would only show up if that constraint was also mixed with a lower bound (`gt`/`ge`) constraint.
```python
Annotated[int, Meta(gt=0, lt=10)]
```
The bug is specific to `lt`, and doesn't appear when using `le`. A workaround to use for past releases is to use `le` instead of `lt` for integer lower bounds.
```python
Annotated[int, Meta(gt=0, le=11)]
```
Fixes #334.
> Fix integer `lt` constraint bug

- msgspec/_core.c
- tests/test_struct.py
Previously using `field()` (with no arguments) to define a struct field would result in a segfault. This PR resolves that issue and adds a test.
Fixes #342.
> Support defining struct with field with no args

- docs/source/supported-types.rst
- msgspec/_core.c
- msgspec/_utils.py
- setup.py
- tests/test_common.py
- tests/test_from_builtins.py
- tests/test_to_builtins.py
This adds support for encoding/decoding attrs types. It's mostly built off of our existing `dataclasses` functionality, and has the same restrictions:
- When encoding, any *object* attribute without a leading underscore is encoded using the attribute name, even if it's not marked as an attribute as part of the class definition. This is for performance reasons, accessing `__attrs_attrs__` at encoding time comes at a perf cost.
- When decoding, the `__init__` method on the class is not called. This is for both efficiency and correctness reasons. As such, classes that define their own `__init__` or `__attrs_init__` will not have this called during the decoding process. `__attrs_pre_init__` and `__attrs_post_init__` methods are called at the proper times though.
- Currently default factories …
> Support encoding and decoding attrs types

- msgspec/inspect.py
- tests/test_inspect.py
- tests/test_schema.py
This adds support for attrs types to `msgspec.json.schema` and `msgspec.inspect.type_info`. This was accidentally missed when support for encoding/decoding these types was added.
> Support attrs types in json schema generation

- msgspec/_core.c
- tests/test_from_builtins.py
This improves the flexibility of `from_builtins` in the following ways:
- Arbitrary input types are now accepted, with the caveat that anything not part of the set of "builtin" types cannot be coerced except to another custom type. This means that you can decode e.g. `bson.ObjectId` objects to `bson.ObjectId`. You can also convert them to another custom type. But you can't decode them to `str`.
- Subclasses of `int` and `bytes` are now accepted, and can be coerced to their base classes (or in the case of int subclasses, other integer-like types like `IntEnum`). These changes are to support mapping `bson.Int64` and `bson.Binary` to `int` and `bytes` respectively. Since these types use `tp_flags` for fast subclass checks, there's little overhead to supporting subclasses like this as inputs. …
> Improve flexibility of `from_builtins`

- docs/source/supported-types.rst
- msgspec/_core.c
- msgspec/_utils.py
- msgspec/inspect.py
- tests/basic_typing_examples.py
- tests/test_common.py
- tests/test_inspect.py
This adds support for `typing.Final` annotations. `Final` can be used to wrap an existing field annotation, marking it as a field that can't be modified once it's initialized. This has the same semantics as `frozen=True`, but only for a single field, and not enforced at runtime.
The `Frozen` annotation may be used to wrap field annotations on any object-like type we support (`msgspec.Struct`, `attrs`, or `dataclasses`).
```python
import msgspec
class Test(msgspec.Struct):
x: Final[int] = 0
t = Test(1)
t.x = 2  # mypy and pyright will complain here
```
---
Note that currently `mypy` has a bug (https://github.com/python/mypy/issues/5608) where `Final` annotations in dataclass-like things require a default value (the bug seems to be early on in mypy's type processing pipeline). This is to …
> Support `typing.Final` annotations

- msgspec/_core.c
- tests/test_struct.py
Fixes #364, Fixes #362.
Both of these were caused by `tp_dealloc` being broken on CPython 3.11+ for structs with `dict=True` enabled. The root cause in both cases was our freelist implementation. Changes to CPython in 3.11 made it pretty much impossible to correctly implement a freelist this way for classes that include a `__dict__` on them. Since the freelist only shaves ~10-20% off allocation costs for a Struct in a hotloop (~5-15ns for typical structs on my machine), we just drop usage of the freelist entirely. It's too hard to maintain now across interpreter versions.
This also adds a new restriction where you can't set `gc=False` & `dict=True`, as correctly freeing `__dict__` values prevents dropping the gc from these types.
> Fix deallocation of Structs with `dict=True` in CPython 3.11

- msgspec/_core.c
- tests/test_struct.py
It's not well documented, but CPython's trashcan mechanism only works for GC types. As such, we drop the usage of the trashcan for Structs with `gc=False`.
> Don't use the trashcan for gc=False structs

- msgspec/_core.c
- tests/test_struct.py
This fixes a bug that previously prevented overriding `__setattr__` in `msgspec.Struct` types.
Fixes #374.
> Support overriding __setattr__ in Struct types

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_json.py
This removes the previous bounds restrictions when encoding integers to JSON. The JSON encoder will now happily encode any integer value.
When decoding, integers that don't fit into an int64/uint64 still decode as floats. I think this limitation is fine, large integers are generally not supported in most languages, and many JSON decoders have the same behavior here.
Fixes #377.
> Support encoding large integers in JSON

- msgspec/_core.c
- tests/test_msgpack.py
This fixes a refcount leak when msgpack decoding variable length tuples with length > 16. This leak was introduced in version 0.14.1.
Fixes #379.
> Fix msgpack memleak when decoding large variable length tuples

- msgspec/_core.c
- msgspec/_json_schema.py
- msgspec/inspect.py
- tests/basic_typing_examples.py
- tests/test_common.py
- tests/test_from_builtins.py
- tests/test_inspect.py
- tests/test_json.py
Previously we spent a lot of effort to detect types that could never be decoded by a JSON decoder (but could be decoded by other protocols), and raised a nicer error at Decoder-initialization-time in this case.
Due to our caching of TypeNodes, the code for doing this was some of the fiddliest bits in msgspec. If a JSON-incompatible type was already parsed and cached to build a MessagePack parser, we'd have to ignore the cached value to retraverse the type to check again.
We delete all this code in favor of erroring at runtime. I don't expect this to degrade usability - the user will still get an error, just at a later point in usage. This simplifies our type parsing code dramatically, making it easier to support new types.
> Remove JSON compatibility checks when building TypeNodes

- msgspec/structs.pyi
- msgspec/toml.py
- msgspec/yaml.py
Not sure why, but the mypy tests have suddenly started failing in CI only. The failure is due to type stubs missing for an optional dependency (the type stubs should only be needed for type checking the internals of `msgspec`, not checking user usage of it). I cannot reproduce these issues locally.
By changing around our type annotations and adding a few `type: ignore` comments, I believe this change should resolve the issues on CI.
> Work around spurious mypy test errors

- .github/workflows/ci.yml
- msgspec/_core.c
- msgspec/_json_schema.py
- msgspec/_utils.py
- msgspec/inspect.py
- msgspec/structs.py
- tests/test_common.py
- tests/test_from_builtins.py
- tests/test_utils.py
This adds full support for encoding/decoding generic `msgspec.Struct` types. Fixes #193.
A quick demo:
```python
from typing import Generic, TypeVar
from msgspec import Struct, json, ValidationError
T = TypeVar("T")
class Paginated(Struct, Generic[T]):
page: int
per_page: int
total_count: int
items: list[T]
class Order(Struct):
item: str
count: int
msg = """
{
"page": 2,
"per_page": 5,
"total_count": 99,
"items": [
{"item": "apple", "count": 3},
{"item": "banana", "count": 2},
{"item": "carrot", "count": 10},
{"item": "durian", "count": 1},
{"item": "eggplant", "count": 4}
]
}
"""
print(json.decode(msg, type=Paginated[Order]))
#> Paginated(
#>     page=2,
#>     per_page=5,
#>     total_count=99,
#>     items=[
#>         Order(item='apple', count=3),
#>         Order(item='banana', …
```
> Add support for Generic Structs

- msgspec/__init__.pyi
- msgspec/_json_schema.py
- msgspec/json.pyi
- msgspec/msgpack.pyi
- msgspec/toml.py
- msgspec/yaml.py
`pyright` doesn't treat `Type` the same as `Type[Any]` or `type` for some reason (while `mypy` does). When we mean any "type", we now use `type` instead of `typing.Type` in the annotation.
Supersedes #385.
> Use `type` instead of `Type` when unparametrized

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_json.py
Previously we always normalized all timezones to UTC when decoding datetime objects. This was for efficiency reasons, as it let us avoid allocating a new `timezone` object on every decode.
However, some code makes use of the actual offset value - normalizing datetimes to UTC loses this information.
This PR removes the timezone normalization; datetimes will now decode into the specified timezone. We also keep a small cache of timezone objects around indexed by their offset. This should help us avoid allocating timezone objects in a hot loop; the assumption being messages containing multiple datetime objects probably all share the same timezone. The timezone cache has the same cache-clearing rules as the string cache (currently cleared every 10 full GC cycles).
Fixes #384.
> Don't normalize timezones to UTC

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
While not strictly RFC4122 compliant, there's some precedent in other systems for supporting decoding UUIDs without hyphens. In particular, Python's `UUID` constructor accepts this form, as does the default serde implementation for Rust's uuid.
Fixes #388.
> Support decoding unhyphenated UUIDs

- msgspec/_json_schema.py
- tests/test_schema.py
Strip leading whitespace from docstrings using [`textwrap.dedent()`](https://docs.python.org/3.11/library/textwrap.html?t#textwrap.dedent). This fixes markdown rendering of multiline docstrings.
Without this, the leading whitespace before each line causes markdown renderers to interpret the entire docstring as a code block, and inline formatting does not work.
> Dedent docstrings

- docs/source/structs.rst
- msgspec/_core.c
- tests/test_struct.py
Previously a struct's tag was generated from its `__name__`. We now generate it from its `__qualname__`, excluding any leading namespaces from nested functions. This means that (nested) structs should be tagged the same if defined dynamically within a function as if they were defined at the top level.
This is a breaking change, but should only affect users making use of tagged nested structs relying on the default tagging behavior. A user falling into this category seems unlikely.
Fixes #395.
> Use `__qualname__` for struct tags

- msgspec/_core.c
- tests/test_common.py
Previously these worked, but the caching behavior was broken in a way where if a `Literal` type containing `None` was used without an object-like type wrapping it then the `None` element would be dropped.
This also refactors some of the internals to reuse error handling code across the various cached parsed types.
> Fix bug when handling `Literal` types containing a literal `None`

- msgspec/_core.c
- tests/test_common.py
- tests/test_json.py
- tests/test_msgpack.py
Previously all top-level functions (`msgspec.json.encode`, `msgspec.json.decode`, ...) were threadsafe, but methods on `Encoder`/`Decoder` objects were not. This resolves this issue, so all functionality in `msgspec` is now threadsafe.
**Breaking Change**: This removes the `write_buffer_size` kwarg to the `Encoder` classes. This was a fringe configuration option of marginal benefit; with the changes to ensure encoding is threadsafe, keeping this around is of negligible benefit. If you really want to minimize allocations during encoding, make use of the existing `Encoder.encode_into` methods instead of increasing the `write_buffer_size`.
Fixes #401.
> Make `Encoder`/`Decoder` methods threadsafe

- msgspec/_utils.py
- tests/test_common.py
Due to a bug in both `typing.TypedDict`/`typing_extensions.TypedDict`, `Required`/`NotRequired` are not properly detected at runtime when `__future__.annotations` is enabled. This means that `TypedDict` definitions making use of these annotations previously couldn't enable `__future__.annotations`. We now parse `Required`/`NotRequired` types manually ourselves, working around the upstream issue.
Fixes #404.
> Support `Required`/`NotRequired` with `__future__.annotations`

- msgspec/_core.c
- tests/test_common.py
Previously `Decoder` types could be parametrized in annotations, but only if `__future__.annotations` was imported (they only worked for static analysis tools like mypy/pyright). We now support parametrizing `Decoder` types in python code without `__future__.annotations` for Python 3.9+.
Fixes #414
> Add support for parametrizing Decoders at runtime

- docs/source/converters.rst
- msgspec/_core.c
- tests/test_from_builtins.py
Previously this was intentionally omitted, as no known Python serialization libraries will return a `set` object from a `loads` method. However, it's easy to support, and if users are using `from_builtins` to coerce from other sources then a `set`/`frozenset` type might pop up.
Fixes #417.
> Support `set` & `frozenset` as inputs to `from_builtins`

- docs/source/converters.rst
- msgspec/__init__.pyi
- msgspec/_core.c
- tests/basic_typing_examples.py
- tests/test_from_builtins.py
This adds a new `attributes` option to `from_builtins`. If enabled, arbitrary objects may be coerced to `Struct`/`dataclasses`/`attrs` types by extracting attributes from the input object matching fields in the output type. One use case is converting database query results (ORM or otherwise) to msgspec structured types.
Fixes #416.
> Add `attributes` option to `from_builtins`

- msgspec/_core.c
- tests/test_from_builtins.py
In #418  we added support for converting set/frozenset inputs to any sequence type. However, since sets/frozensets are unordered, we shouldn't convert these to sequences where the order matters. We now limit `from_builtins(<set>, ...)` to convert to `set`, `frozenset`, `list`, or variable length `tuple` types.
> Don't convert sets to ordered types in `from_builtins`

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_to_builtins.py
This lets msgspec work out-of-the-box with `asyncpg.pgproto.pgproto.UUID` types, rather than requiring these be handled with `enc_hook`.
Fixes #428.
> Support encoding UUID subclasses

- benchmarks/bench_encodings.py
- benchmarks/bench_validation.py
- docs/source/supported-types.rst
- docs/source/usage.rst
- msgspec/_core.c
- msgspec/json.pyi
- msgspec/msgpack.pyi
- msgspec/toml.py
- msgspec/yaml.py
- tests/basic_typing_examples.py
- tests/test_common.py
- tests/test_toml.py
- tests/test_yaml.py
This adds a new `strict` boolean config kwarg to all `decode` functions (as well as all `Decoder` classes). The default is `True`, matching the existing strict type coercion rules. Setting to `False` enables a wider set of coercion rules, which may be useful in some scenarios. Currently setting `strict=False` enables coercing:
- the string `"null"` (case insensitive) to `None`
- the strings `"false"` or `"0"` (case insensitive) to `False`
- the strings `"true"` or `"1"` (case insensitive) to `True`
- any int-like string to an integer
- any float-like string to a float
Additional coercion rules may be added to `strict=False` ("lax mode") in the future.
Note that coercion still only happens if the requested type (e.g. `int`) doesn't match the provided type (e.g. `str`). When not using …
> Support `strict` setting in all decoders

- msgspec/_core.c
- tests/test_convert.py
Previously when converting a value to an `Any` type, we'd recurse through the input if the input was a known builtin type. We now return the input unchanged when converting to an `Any` field. This is significantly more efficient in these cases, as it doesn't require recursing through the input data.
> Passthrough input unchanged for `convert` to `Any` type

- msgspec/__init__.pyi
- msgspec/_core.c
- tests/basic_typing_examples.py
- tests/test_struct.py
Previously these kwargs were documented as accepting `None`, but passing in `None` wasn't actually supported. This PR fixes this, and adds a test checking this behavior.
Fixes #444.
> defstruct accepts None for module/namespace/bases

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_convert.py
- tests/test_msgpack.py
This adds support for decoding float/int/numeric-strings into datetime objects when `strict=False`. These inputs are interpreted as epoch timestamps (seconds since the epoch, UTC), and are decoded as timezone-aware with a UTC timezone.
```python
In [1]: import msgspec
In [2]: import datetime
In [3]: dt = datetime.datetime.now()
In [4]: ts = dt.timestamp()
In [5]:
Out[5]: 1687578573.501321
In [6]: msgspec.convert(ts, type=datetime.datetime)  # by default not supported
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[6], line 1
----> 1 msgspec.convert(ts, type=datetime.datetime)
ValidationError: Expected `datetime`, got `float`
In [7]: msgspec.convert(ts, type=datetime.datetime, …
```
> Support decoding unix timestamps to datetimes when `strict=False`

- msgspec/_core.c
- tests/test_convert.py
We now support passing subclasses of collection types (`list`, `tuple`, `set`, `frozenset`, `dict`) as inputs to `convert`. In particular, this makes passing SQLAlchemy output to `convert` easier to work with.
Fixes #451.
> Support collection subclasses as inputs to convert

- msgspec/_core.c
- tests/test_json.py
- tests/test_msgpack.py
- tests/test_to_builtins.py
Previously we only supported `str` types exactly, or types that would be natively mapped to `str`. We now natively support `str` subclasses as dict keys in `msgspec.to_builtins` as well as all `encode` functions.
This is a bit inconsistent with the rest of msgspec, where `str` subclasses aren't natively supported and require an `enc_hook` to support. I think making an exception for dict keys is fine since:
- In the long term the `enc_hook` design should be reworked, allowing us to natively handle `str` subclasses everywhere, provided the user doesn't override a serializer for that type. When that's done dicts with str subclasses as keys will "just work" out of the box, I see no reason not to allow that now as well.
- The main reason we don't natively support encoding str subclasses (or …
> Support str subclasses as dict keys in encode/to_builtins

- msgspec/_core.c
No need to do a full str encode pass here, the generated strings should never need escaping.
> Improve JSON decimal encode performance

- msgspec/_core.c
- msgspec/itoa.h
- msgspec/ryu.h
This further optimizes the JSON encoding of integers and floats.
> Optimize JSON encoding of numbers

- msgspec/_core.c
- tests/test_json.py
This improves the performance of encoding JSON strings, mostly by rearranging some work and unrolling some loops.
> Improve JSON str encode performance

- docs/source/extending.rst
- msgspec/_core.c
- msgspec/toml.py
- msgspec/yaml.py
- tests/test_common.py
- tests/test_convert.py
- tests/test_json.py
- tests/test_msgpack.py
This modifies decoding of custom types to wrap errors raised by a `dec_hook` with `ValidationError`. Only `TypeError` or `ValueError` (and subclasses) exceptions are wrapped, all other exceptions are raised directly.
If an exception is wrapped with a `ValidationError`, the original exception is set as the `__cause__` (and `__context__`). This means the original exception will still show up in tracebacks, and is available for introspection if needed.
This also changes the recommendation for raising `TypeError` on unsupported types in `dec_hook`/`enc_hook` to raising a `NotImplementedError`. No previous functionality was based on this recommendation, so this isn't a breaking change in anyway, just a change in recommendation of how best to use `msgspec`.
Fixes #456.
> Wrap dec_hook errors in `ValidationError`

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_convert.py
- tests/test_json.py
This adds support for converting int/float inputs to `decimal.Decimal` types for all protocols' `decode` methods, as well `msgspec.convert`.
The intent of this is to provide more flexible input support for `decimal.Decimal` types, since not everyone wants to encode them as strings.
For JSON fields there is no loss of precision, the numeric representation is parsed directly into the Decimal object, same as if it was a string.
For all other protocols, there is a possibility of precision loss, when converting from float -> decimal. We don't pass the value directly to `decimal.Decimal`, but instead convert to a str expressing the shortest roundtrippable value for the IEEE754 decimal. This is effectively equivalent to
```
if isinstance(input, float):
return decimal.Decimal(str(input))
```
In …
> Support decoding `Decimal` types from numeric (int/float) values

- docs/source/supported-types.rst
- msgspec/_core.c
- msgspec/json.pyi
- msgspec/msgpack.pyi
- tests/basic_typing_examples.py
- tests/test_common.py
- tests/test_json.py
Previously we always encoded `decimal.Decimal` values as strings. While this is the best format for these types (prevents precision loss, widely supported), sometimes there is a need to encode `Decimal` objects the same as numbers. This adds a new `decimal_format` option to all `Encoder` classes. This value defaults to `"string"` (to encode decimals as strings), but may be set to `"number"` to encode them the same as the protocol's numeric types.
We opt not to support this configuration in the top-level `encode` functions for now, since this is a less-common setting.
Fixes #440.
> Support encoding decimals as numbers

- .github/workflows/ci.yml
- msgspec/_core.c
- tests/test_common.py
- tests/test_convert.py
This fixes compatibility with cpython 3.12's beta releases. For the most part this was an uneventful release, the two major issues were:
- CPython 3.12 changed the internal representation of integers, which we (probably unadvisably) poke at.
- The idiom for statically declaring instances of singleton values (like `None`) has changed. We use this for declaring `msgspec.NODEFAULT`/`msgspec.UNSET`.
Fixes #462.
> Support CPython 3.12 pre-releases

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_constraints.py
- tests/test_convert.py
- tests/test_json.py
Previously all `decode` methods would only support integers that fit in a `uint64`/`int64`. This PR removes that restriction for everything _except_ MessagePack which as a binary protocol cannot support arbitrarily large integers.
To handle the parsing of these "big ints" we use CPython's builtin `str -> int` routine. This is slower than our custom `str -> int` function, but since integers of this scale are rare this should be fine in practice.
Note that currently CPython's `str -> int` routine exhibits quadratic behavior in the length of its input. This led to a DDOS CVE which was mitigated in 3.11 by adding a configurable max str length for int parsing. We hardcode the limit of 4300 chars here to support older python versions, while still properly handling cases where the user may have …
> Support decoding ints outside int64/uint64

- docs/source/structs.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_convert.py
- tests/test_struct.py
This adds support for an optional `__post_init__` hook method on `msgspec.Struct` types. If defined, this method is called at the end of the generated `__init__` method. It can be used to customize the builtin `__init__` as needed, as well as provides a spot to do some additional validation.
As with `dec_hook` errors, any `ValueError` or `TypeError` raised in `__post_init__` will be wrapped in a `ValidationError` when decoding. In the long run I plan to add support for more granular (and obviously named) custom validator support, but for now doing some validation in `__post_init__` is a fine and simple solution. There are other use cases for `__post_init__` besides validation, so we'd want to add this ability either way.
Fixes #442.
> Support `__post_init__` for `Struct` types

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_convert.py
Previously we only supported mapping *string* versions of `1`/`0` to `True`/`False` in lax mode. This adds support for mapping the integer values as well.
> Support decoding 1/0 into True/False in lax mode

- msgspec/_core.c
- tests/test_common.py
- tests/test_convert.py
When decoding/converting to a dataclass/attrs type with a `__post_init__`/`__attrs_post_init__` method, we now wrap all `ValueError`/`TypeError` exceptions in a `ValidationError`. This mirrors the behavior used in the new `Struct.__post_init__` support, and helps provide more uniform error handling support.
> Wrap errors in dataclass/attrs post-init methods

- benchmarks/bench_validation.py
Hi, author of mashumaro here 👋
I appreciate your work and I don't think anyone could outrun msgspec in speed but I found a bug in how mashumaro is benchmarked. Due to [how mashumaro works](https://github.com/Fatal1ty/mashumaro#how-does-it-work), it tries to compile methods `from_*` / `to_*` at import time by default but if it fails because of forward references, then these methods will consist of the code that will compile the real methods and replace with them on demand. In the original benchmark there were forward references due to `from __future__ import annotations` which were leading to expensive compilation on each call of `from_*` / `to_*`.
I fixed this with lambda functions and added ~[discriminated unions](https://github.com/Fatal1ty/mashumaro#discriminator) and~ [explicit lazy …
> Fixed recompilation in mashumaro

- docs/source/api.rst
- docs/source/supported-types.rst
- msgspec/_core.c
- msgspec/_json_schema.py
- msgspec/inspect.py
- tests/test_common.py
- tests/test_convert.py
- tests/test_inspect.py
- tests/test_schema.py
- tests/test_to_builtins.py
This adds builtin timedelta support.
By default, we encode-to/decode-from a subset of [ISO 8601 duration strings](https://en.wikipedia.org/wiki/ISO_8601#Durations).
This subset matches the intersection between the one used by [java's duration](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Duration.html#parse(java.lang.CharSequence)), and the proposed javascript `Temporal.Duration` api ([docs here](https://tc39.es/proposal-temporal/docs/duration.html)). Duration strings produced by msgspec should be compatible with either of these libraries (and most other ISO 8601 compatible systems). Likewise, durations produced by those libraries should be readable by msgspec. See the included docs update for a complete spec of what ISO8601 subset is supported.
We _might_ want …
> `datetime.timedelta` Support

- docs/source/api.rst
- msgspec/_core.c
- msgspec/json.pyi
- tests/basic_typing_examples.py
- tests/test_json.py
This adds a new method on the JSON `Encoder` class for encoding an iterable of items as newline delimited JSON, one item per line. This is roughly equivalent to (but up to 3x faster than):
```python
def encode_lines(items):
return b''.join(
msgspec.json.encode(item) + b'\n' for item in items
)
```
We limit it to an implementation on the `Encoder` class alone for now (rather than a new top-level function) since this is a relatively niche feature.
Fixes #449.
> Add `msgspec.json.Encoder.encode_lines`

- docs/source/supported-types.rst
- msgspec/_core.c
- msgspec/json.pyi
- msgspec/msgpack.pyi
- tests/basic_typing_examples.py
- tests/test_common.py
- tests/test_convert.py
- tests/test_msgpack.py
This adds a new `uuid_format` to the json and msgpack encoders, configuring how msgspec will handle uuids. This may be one of:
- `canonical`: UUIDs are encoded as canonical strings (same as `str(uuid)`). This is the default.
- `hex`: UUIDs are encoded as strings without hyphens (same as `uuid.hex`).
- `bytes`: UUIDs are encoded as binary values representing big-endian 128-bit integers (same as `uuid.bytes`).
All protocols support decoding from any of these formats by default. Note that only msgpack supports encoding/decoding the `'bytes'` value, as JSON lacks a native binary type.
```python
In [1]: import msgspec
In [2]: import uuid
In [3]: u = uuid.uuid4()
In [4]: u
Out[4]: UUID('827ba710-601d-421c-bdaf-632d2db2620c')
In [5]: msgspec.json.encode(u)  # defaults to canonical
Out[5]: …
```
> Support alternative UUID formats.

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_to_builtins.py
Previously we supported encoding dataclasses (determined as any object with a `__dataclass_fields__` attribute), provided those objects were implemented in a way similar-enough to how they were implemented in the standard library. The intent was to support stdlib dataclasses, and if alternative implementations (e.g. `pydantic.dataclasses`) happened to work then all the better.
However, due to how we were detecting if an object was a dataclass, there was no way to override our builtin support if an alternative implementation (in this case `edgedb.Object`) didn't work.
To fix this, we now make fewer assumptions about how the backing dataclass object is implemented.
Pros:
- We can now natively encode objects implemented using `dataclasses`, `pydantic.dataclasses`, and `edgedb.Object`.
- We …
> Support encoding more dataclass-like things

- docs/source/supported-types.rst
- msgspec/_core.c
- msgspec/atof.h
- msgspec/ryu.h
- tests/test_common.py
- tests/test_convert.py
- tests/test_json.py
- tests/test_to_builtins.py
This refactors the number parsing routine (str -> int/float), with the following results:
- Improved performance, up to 20% faster, dependent on message. This is most prominent for floats or long ints.
- Ability to reuse the same routine for converting strings to ints or floats (or int/float-like things). Previously we had a duplicate `str -> int` routine, and relied on cpython's float parser for the `str -> float` conversions. With this change we're able to delete a bunch of code.
- Expanded features. In particular, we can now support float-like strings as dict keys in JSON.
- Improved maintainability. The reorganized code should provide a better base to build new features off of.
This also adds support for encoding dicts with floats as keys (the keys are encoded as strings).
> Refactor float parsing

- msgspec/_core.c
- msgspec/json.pyi
- tests/basic_typing_examples.py
- tests/test_json.py
This adds support for a `float_hook` to the json decoder. If set, this hook will be called to decode any untyped JSON float values from their raw string representations. This may be used to change the default float parsing from returning ``float`` values to return ``decimal.Decimal`` values again.
Since this is an uncommon option, it's only available on the Decoder, rather than the top-level ``msgspec.json.decode`` function.
Fixes #507.
> Add `float_hook` to json decoder

- msgspec/_core.c
- tests/test_to_builtins.py
This adds support for "custom" `builtin_types` in `to_builtins`. This is useful when wrapping a protocol like `bson` that has protocol specific types like `ObjectId` that you'll want to pass through unchanged.
For example, to support passing `bson.ObjectId` through `msgspec.to_builtins`:
```python
In [1]: import msgspec, bson
In [2]: class Point(msgspec.Struct):
...:     _id: bson.ObjectId
...:     x: int
...:     y: int
...:
In [3]: obj = Point(bson.ObjectId(), 1, 2)
In [4]: obj
Out[4]: Point(_id=ObjectId('64dad4a21ffe3dbdae50a48e'), x=1, y=2)
In [5]: msg = msgspec.to_builtins(obj, builtin_types=(bson.ObjectId,))
In [6]: msg
Out[6]: {'_id': ObjectId('64dad4a21ffe3dbdae50a48e'), 'x': 1, 'y': 2}
In [7]: msgspec.convert(msg, type=Point)
Out[7]: …
```
> Support custom `builtin_types` in `to_builtins`

- docs/source/supported-types.rst
Adds some callouts to the `dataclasses` and `namedtuple` docs sections illustrating that `edgedb.Object`/`edgedb.NamedTuple` types are natively supported.
> Document edgedb type support

- msgspec/_core.c
- tests/test_convert.py
Previously if a mapping was passed to `convert`, values would only be extracted via `PyObject_GetItem` even if `from_attributes=True`. Some object types define `__getitem__` but also store data via attribute. In this case we want to try `PyObject_GetAttr` first, falling back to `PyObject_GetItem`.
> Try `getattr` first in `convert(mapping, from_attributes=True)`

- msgspec/_core.c
Top-level functions defined using the c-api have the module object passed as `self`, there's no need to go through `PyState_FindModule` for these functions.
This shaves ~5 ns off the call time per function, which is ~6% of the overhead of a `msgspec.json.encode` call.
> More efficient module state access in top-level functions

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_convert.py
This adds support for `Enum._missing_` hooks. This method is part of the standard library's `enum` implementation, and is called when a value isn't one defined directly on the `Enum` type. The method should return a valid enum member, or `None` if the value is invalid.
This may be used to support case-insensitive enums, or to coerce unknown values into a single "UNKNOWN" member.
Fixes #531.
> Support `Enum._missing_` hooks

- msgspec/_core.c
- tests/test_common.py
- tests/test_json.py
This fixes a bug where datetime objects with `zoneinfo.ZoneInfo` instances set for `tzinfo` would encode as UTC, ignoring the zoneinfo. This issue was due to `datetime.utcoffset` being called with `None` instead of the `datetime` instance. This worked fine for other `tzinfo` types (like `datetime.timezone`) since those use fixed offsets that aren't date aware.
This also fixes a bug where `datetime.time` instances with a `tzinfo` that returns `None` from `datetime.time.utcoffset` were treated as UTC rather than naive. Quoting from the [standard library docs](https://docs.python.org/3/library/datetime.html#determining-if-an-object-is-aware-or-naive):
> A datetime object d is aware if both of the following hold:
>
> 1. d.tzinfo is not None
> 2. d.tzinfo.utcoffset(d) does not return None
>
> …
> Fix JSON encoding of datetimes with zoneinfo tzinfos

- docs/source/supported-types.rst
- msgspec/_utils.py
- tests/test_common.py
This adds support for attrs validators. Validators are run after decoding the instance has completed, but before calling `__attrs_post_init__`. Since the builtin attrs validators include the attribute name in the error message, we don't add the field to the error path. This feels *a bit* weird, but is way easier since all of this can be done in pure python.
When possible, it'd be better to use msgspec's builtin constraints for handling validation. These will be much more performant, and integrate better with the rest of the system.
Fixes #535.
> Support attrs validators

- msgspec/_core.c
- tests/test_common.py
- tests/test_json.py
Previously we strictly followed the RFC3339 format when parsing datetime and time objects from strings. We now support a few common ISO8601 compatible relaxations:
- A `:` isn't required as part of the timezone component in both datetime and time strings (`2022-01-02T03:04:05.678+0102` and `2022-01-02T03:04:05.678+01:02` are treated the same).
- A ` ` may be used instead of `T`/`t` as a separator between date and time components when parsing datetime strings (`2022-01-02 03:04:05.678+01:02` and `2022-01-02T03:04:05.678+01:02` are treated the same).
When encoding datetime/time objects we still strictly follow RFC3339. This eases integrating msgspec with other systems that don't strictly follow RFC3339.
Fixes #537.
> Relaxed datetime/time parsing

- docs/source/supported-types.rst
Fixes
```
msgspec.ValidationError: Object missing required field `items`
```
> docs: update Generic Type example in supported-types.rst

- msgspec/__init__.pyi
- tests/basic_typing_examples.py
> Fix `__rich_repr__` type annotation

- msgspec/_core.c
Python 3.12 changed module init slightly (this may actually be a CPython 3.12 bug, it's not 100% clear). Before Python 3.12 the module wouldn't be available via `PyState_FindModule` until it was fully initialized. Now the module is immediately available, but in an invalid state leading to segfaults. The workaround is to manually call `PyState_AddModule` to ensure the module is always available.
In the long run we should move to using multiphase module init which should avoid this problem entirely.
> Fix module init for Python 3.12

- msgspec/inspect.py
- tests/test_inspect.py
This PR handles the case where `t` in the call to  `_CONCRETE_TYPES.get(t)` is not hashable, such as when an `Annotated` instance contains unhashable metadata.
Closes #565
> Handle where `Annotated` has unhashable metadata.

- msgspec/_core.c
- tests/test_common.py
- tests/test_convert.py
Previously there was a bug where dataclasses or attrs classes with `slots=True, frozen=True` wouldn't be able to properly use default values for optional fields.
Fixes #567.
> Fix bug handling default values for frozen & slotted dataclasses

- msgspec/structs.py
- tests/test_struct.py
Previously `msgspec.structs.fields` only worked on struct instances or types. We now also support parametrized generic struct types, so `msgspec.structs.fields(MyStruct[int])` also works.
Fixes #570.
> `msgspec.structs.fields` works on parametrized generics

- msgspec/_core.c
- tests/test_constraints.py
Previously the msgpack decoder would miss checking constraints on dict keys if those keys were short ascii strings. This fixes that and adds a test.
This issue was pointed out in #576.
> Check str constraints on dict keys in msgpack

- msgspec/_core.c
- tests/test_convert.py
This fixes a bug where UUID subclasses weren't supported as inputs to `msgspec.convert`.
> Support UUID subclasses in `convert`

- msgspec/_core.c
- tests/test_struct.py
If a user manually defines an `__eq__` for a `Struct` class, the default `__ne__` implementation will now call the user-defined `__eq__` and invert the result, rather than applying the standard `__ne__` logic. This makes it easier for users to manually override `__eq__`, and matches the behavior of standard python classes.
Fixes #585.
> Call `__eq__` from `__ne__` for user defined `__eq__`

- msgspec/_core.c
- tests/test_struct.py
This modifies the provided hash method to also include the struct type. This improves hash quality for mappings or sets that contain multiple different struct types as keys, as structs of different types with the same data will now hash differently, better matching the `__eq__` implementation.
As an implementation detail, structs should now hash as a tuple of the type and all following elements.
```python
from msgspec import Struct
class Point(Struct, frozen=True):
x: int
y: int
assert hash(Point(1, 2)) == hash((Point, 1, 2))
```
Addresses part of #591.
> Include the struct type in frozen hash implementation

- msgspec/__init__.pyi
- msgspec/_core.c
- msgspec/structs.pyi
- tests/basic_typing_examples.py
- tests/test_struct.py
If enabled, the hash value for a frozen struct instance will be computed at most once, and then stored on the instance for further reuse. For expensive hash computations this can result in improved performance at the cost of a small amount of memory use.
Fixes #591.
> Add struct `cache_hash` option

- msgspec/_core.c
- tests/test_common.py
Previously our caching mechanism would do the wrong thing when accessing type info on a dataclass subclass when the base class info was already cached. This fixes that so that decoding dataclass subclasses always works properly.
Fixes #598.
> Fix caching of dataclass subclass info

- msgspec/_core.c
- tests/test_json.py
This adds support for encoding/decoding custom types when used as dict keys in the JSON encoder/decoder. Previously the JSON implementation failed to fallback to `enc_hook`/`dec_hook` for custom dict keys.
Fixes #568.
> Support custom dict key types in JSON

- msgspec/_json_schema.py
- tests/test_schema.py
This adds support for publicizing constraints on dict keys using the `propertyNames` field when generating a JSON Schema. For now this is only done for dicts with string keys; constraints on other key types are trickier to specify.
Supersedes #576.
> Pass key constraints as `propertyNames` in JSON Schema

- docs/source/supported-types.rst
- msgspec/_core.c
- msgspec/inspect.py
- tests/test_common.py
- tests/test_convert.py
- tests/test_inspect.py
This adds support for the new syntactic type aliases added in Python 3.12. A few examples:
```
type NullableStr = str | None
type Pair[T] = tuple[T, T]
type NullableStrPair = Pair[NullableStr]
```
msgspec now supports these type aliases, *except* in cases where the type alias is recursive. For example, the following type isn't supported:
```
type Link[T] = tuple[T, Link[T] | None]
```
The internal datastructure we use to store type information was not designed to handle recursive types like these; supporting them will require a larger refactor.
Fixes #579.
> Add support for Python 3.12's `type` aliases

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_convert.py
This adds a path for coercing floats to ints if `strict=False`, provided the float has an exact integral representation.
```python
>>> import msgspec
>>> msgspec.convert(1.0, int, strict=False)
1
>>> msgspec.convert(1.5, int, strict=False)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
msgspec.ValidationError: Expected `int`, got `float`
```
Fixes #613.
> Support coercing float to int if `strict=False`

- msgspec/_core.c
- tests/test_struct.py
Previously leading underscores were stripped when renaming fields to a `camelCase` or `PascalCase` convention. We now preserve leading underscores, better matching the behavior and conventions of other libraries.
Before: `_field_one` -> `fieldOne`
Now: `_field_one` -> `_fieldOne`
Fixes #618.
> Preserve leading `_` for camel/pascal renaming

- msgspec/_core.c
This fixes a refcounting bug with `rename="camel"` that was introduced in #620.
> Fix refcounting bug introduced in previous commit

- docs/source/api.rst
- docs/source/supported-types.rst
- msgspec/_core.c
- msgspec/_json_schema.py
- msgspec/inspect.py
- tests/test_constraints.py
- tests/test_convert.py
- tests/test_inspect.py
- tests/test_json.py
- tests/test_msgpack.py
- tests/test_schema.py
The implementation enables zero-copy functionality when decoding msgpack by supporting deserialization directly to a memoryview. This is very useful for decoding large numpy array.
> feat: support deserializing to memoryview

- msgspec/_utils.py
- tests/test_utils.py
Previously if the same generic base class appeared multiple times in a classes inheritence graph msgspec would error when trying to analyze the class. This PR fixes the bug and adds a test for the behavior.
Fixes #625.
> Fix bug with multiple generic inheritence

- msgspec/__init__.pyi
- msgspec/_core.c
- msgspec/json.pyi
- msgspec/msgpack.pyi
- msgspec/toml.py
- msgspec/yaml.py
- tests/basic_typing_examples.py
- tests/conftest.py
- tests/test_common.py
- tests/test_json.py
- tests/test_to_builtins.py
- tests/test_toml.py
- tests/test_yaml.py
Add `order` kwarg to encoders
This adds an `order` kwarg to all encoders for configuring how unordered
collections/objects are encoded. Options are:
- `None`: the default. All objects are encoded in the most efficient
manner corresponding to their in-memory representation.
- `'deterministic'`: Unordered collections (sets, dicts) are sorted
before encoding. This ensures a consistent output between runs, which
may be useful when comparing/hashing the encoded binary
representation.
- `'sorted'`: same as `'deterministic'`, but *all* objet-like objects
will have their fields encoded in alphabetical order by name. This is
more expensive than `'deterministic'`, but may be useful for making
the output more human readable.
The `'deterministic'` output has been heavily optimized - given the work …
> Add `order` option to encoders

- msgspec/_core.c
- tests/test_convert.py
Struct types support renaming of fields for encoding/decoding. A common use of this is to enforce a camelCase convention in the serialized format:
```python
import msgspec
class Example(msgspec.Struct, rename="camel"):
field_one: int
field_two: int
x = Example(1, 2)
print(msgspec.json.encode(x))
#> b'{"fieldOne":1,"fieldTwo":2}
```
Previously when converting an object to a struct we'd always use the renamed field names rather than the original names. This was true whether the input was a `dict`, a non-dict mapping, mapping, or an arbitrary object via attributes if `from_attributes=True`. The latter two inputs will rarely/never occur when coming from a serialization framework, but are more commonly used with database/ORM-like objects. In this case it's more likely that the *original* …
> Infer naming convention when converting objects to structs

- tests/test_performance.py
This adds a test from [this pydantic issue](https://github.com/pydantic/pydantic/issues/8499) to ensure that we don't error out when processing deeply recursive schemas with unions. No code change is needed at this time, we process this schema efficiently already.
> Add a deeply recursive schema/union test

- .github/workflows/ci.yml
- tests/test_common.py
- tests/test_convert.py
- tests/utils.py
This adds a test case [found in the `orjson` repo](https://github.com/ijl/orjson/issues/458) to ensure that we properly respect recursion limits when encoding or decoding deeply recursive messages.
No code change is needed at this time, we properly manage recursion limits already.
> Add tests for encoding/decoding highly recursive messages

- msgspec/_core.c
- msgspec/itoa.h
- msgspec/ryu.h
An assortment of micro-optimizations and cleanups around JSON encoding:
- Accelerated `int` and `float` encoding by up to ~2x for small numbers
- Accelerated `datetime`, `date`, and `time` encoding by ~30-40%
- A few code cleanups to simplify the JSON encoder handlers
> JSON encoding speedups

- msgspec/_core.c
- tests/test_common.py
Previously `omit_defaults` would only detect `tuple`/`frozenset` fields containing default values if the default was specified by value.
```python
class Ex(msgspec.Struct, omit_defaults=True):
x: tuple = ()                                    # omit_defaults would work properly with this spelling
y: tuple = msgspec.field(default=())             # or with this spelling
z: tuple = msgspec.field(default_factory=tuple)  # but not with this spelling
```
We now also support if these types are specified via `default_factory` (all 3 cases above now properly work with `omit_defaults=True`).
Note that since `tuple` and `frozenset` values are immutable there's no real reason to prefer `default_factory` for defaults of these types.
Fixes #652.
> `omit_defaults` supports specifying `tuple`/`frozenset` default values via `default_factory`

- msgspec/_core.c
"match_args" is set in StructMetaInfo and eventually StructMeta via -
```
info->match_args = PyTuple_GetSlice(info->fields, 0, nfields - nkwonly);
```
This is incref'd before copying to StructMeta, and decref'd when cleaning up StructMetaInfo. There's no corresponding decref for StructMeta itself. This causes a leak that valgrind readily detects:
```
env PYTHONMALLOC=malloc valgrind python3 -c 'import msgspec'
...
==576283== LEAK SUMMARY:
==576283==    definitely lost: 1,608 bytes in 26 blocks
```
With the fix in place, we get:
```
==576086== LEAK SUMMARY:
==576086==    definitely lost: 0 bytes in 0 blocks
```
> Plug leak of "match_args" in StructMeta.

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- msgspec/__init__.pyi
- msgspec/json.pyi
- msgspec/msgpack.pyi
- msgspec/toml.py
- msgspec/yaml.py
- tests/basic_typing_examples.py
decode can take any type support buffer protocol, not bytes only
> fix msgpack decode function sig

- msgspec/_core.c
- tests/test_raw.py
Raw_New borrows a reference to its PyBytesObject argument, so Raw_Copy must still dispose of it.
The following is a minimal repro for this issue:
```
import msgspec
DECODER = msgspec.msgpack.Decoder(type=msgspec.Raw)
PAYLOAD = b"\xda\xff\xff" + (65535 * b"\0") # array of 65535 zeros
for _ in range(1000000):
raw = DECODER.decode(PAYLOAD)
raw.copy()
```
> Fix memory leak in Raw.copy().

- .github/workflows/ci.yml
- msgspec/_core.c
- msgspec/_utils.py
- setup.cfg
- setup.py
I can close this if https://github.com/jcrist/msgspec/pull/703 gets more attention, but I've confirmed changes here allow the wheels to be built in 3.8-3.13, and all tests are passing.
This warning is currently raised, but fixing it might be beyond the scope of this PR:
```
PytestUnraisableExceptionWarning: Exception ignored in PyDict_GetItem(); consider using PyDict_GetItemRef() or PyDict_GetItemWithError(): None
```
https://github.com/python/cpython/issues/106004
- Closes #698
- Closes #741
> Build Python 3.13 wheels (not free-threaded)

- msgspec/_core.c
- tests/test_struct.py
Previously we were incorrectly accessing `tp_dict` in mixin classes when defining a `Struct` class on Python 3.12+. This could result in a segfault if a user tried to create a `Struct` class that also subclassed from an interpreter builtin type (like `Exception`). Now we error nicely instead.
Fixes #727.
> Use `PyType_GetDict` in Python 3.12+

- docs/source/structs.rst
- msgspec/_core.c
- tests/test_struct.py
This lets structs work with `copy.replace` (added in Python 3.13). Our own `msgspec.structs.replace` also continues to work.
Fixes #713.
> Generate `__replace__` method on `Struct` types

- msgspec/_core.c
- tests/test_json.py
Previously our 64 bit integer overflow detection logic was broken for a range of 65 bit integers between `(2 ** 64) + (10 ** 18) + 1` and `19999999999999999999` (inclusive). This PR fixes this overflow detection logic and improves the test coverage of certain big integers.
Fixes #701.
> Fix JSON decoding of > 64 bit integers

- msgspec/_core.c
- tests/test_convert.py
Previously a struct's `__post_init__` method wouldn't be called when converting from a custom mapping or object with `from_attributes=True`. This PR fixes that and expands the tests to cover this case.
Fixes #673.
> Call `__post_init__` when converting struct from object

- msgspec/_core.c
- tests/test_json.py
- tests/test_msgpack.py
Previously we'd truncate `offset = len(buf)` if `offset > len(buf)` when calling `encode_into(msg, buf, offset)`. We now expand the size of `buf` to `offset`, providing a more consistent and expected behavior.
Fixes #697.
> Change behavior of `encode_into` with `offset` > `len(buf)`

- msgspec/_core.c
- tests/test_convert.py
Previously `Raw` inputs weren't supported in `convert`, now they are.
Fixes #699.
> Support `Raw` in `convert`

- msgspec/_core.c
- tests/test_common.py
- tests/test_to_builtins.py
Previously our "is this a dataclass-like thing" check would erroneously pass for dataclass _classes_ as well as their instances. We now properly exclude classes and only encode instances.
Fixes #681.
> Don't encode dataclass classes

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- msgspec/_core.c
- msgspec/_utils.py
- setup.py
- tests/conftest.py
- tests/test_common.py
- tests/test_constraints.py
- tests/test_convert.py
- tests/test_inspect.py
- tests/test_json.py
- tests/test_schema.py
- tests/utils.py
Python 3.8 is now marked end-of-life: https://devguide.python.org/versions/.
> Drop Python 3.8 support

- docs/source/supported-types.rst
- msgspec/_core.c
- tests/test_common.py
- tests/test_to_builtins.py
Previously we only supported encoding and decoding enums with integer or string values. We now support encoding enums with any value that is also a supported type. The restriction on decoding only integer or string values remains.
Fixes #680.
> Support encoding any enum type whose value is supported

- msgspec/_core.c
https://github.com/python/cpython/pull/125251 renamed _PY_IMMORTAL_REFCNT -> _PY_IMMORTAL_INITIAL_REFCNT
> MNT: account for CPython 314 changes

- msgspec/_core.c
When removing Python 3.8 support, I missed a few lines of Python 3.8-specific backports.
> Remove some missed Python 3.8 code

- msgspec/_utils.py
- tests/test_utils.py
> Don't fail when parsing types with invalid `__parameters__`

- .github/workflows/ci.yml
- msgspec/_utils.py
- setup.py
- tests/test_utils.py
- tests/utils.py
This uses the same module that pydantic does, and it allows people to use the
new pipe syntax if they have to support Python3.9 too -- very useful for
libraries.
(Also it works better with many type checkers which seem to mistakenly think
that with `from __future__ import annotations` means `int| None` will work,
but it doesn't out of the box.)
Fixes #771
> Use eval_type_backport on Python 3.9 if it's installed to resolve `int | None` etc.

- .github/workflows/ci.yml
- setup.py
@jcrist, in my recent testing with Python 3.13, msgspec, and Litestar, I found myself needing binary wheels to speed things up.
There were a few GH actions that have implemented breaking changes, and this PR has the minor updates required to publish releases.
> chore(build): updated Github CI Actions

- msgspec/_core.c
- tests/test_msgpack.py
Previously we would update the exposed `len` but not the `shape`. This went unnoticed since many consuming APIs only check `len` and not `shape`. This fixes the bug and adds some tests to ensure both fields are properly set.
Fixes #835.
> Set shape on exported memoryviews
