jcrist/msgspec

.github/workflows/ci.yml

Not sure if this actually works, will require testing during next
release.

Add a release-to-pypi workflow

---

msgspec/core.c

Full explanation here: https://gist.github.com/llllllllll/b3ccc744e88c5bf0ee4e2c16c6fcdebf
I realize that these changes make the code harder to read, so I understand if you don't think the minor performance improvements are worth it. I figured I would share what I did in case you did want it.

Json encoder optimizations

---

msgspec/_core.c
tests/test_enum.py

This optimizes the decoding of Enums, following the same pattern
recently implemented for `IntEnum` types. A custom hashtable object is
generated once per Enum object and stored on the class as the
`__msgspec_lookup__` attribute. The hashtable maps each enum name to its
value, and allows us to lookup the enum values without allocating a
temporary string object and using it to lookup the enum value.
Using this method, I get a 10x speedup on decoding enums. This
implementation will also be used in a follow-up PR for implementing
decoding of `Literal` string types.

Speedup decoding of Enum types

---

docs/source/usage.rst
msgspec/_core.c
tests/test_enum.py
tests/test_json.py
tests/test_msgpack.py

Support literal types

---

docs/source/perf-tips.rst
docs/source/structs.rst
docs/source/usage.rst

A few small doc fixups

---

.github/workflows/ci.yml
.pre-commit-config.yaml

- Add pre-commit configuration to automatically run flake8 & black on
commit
- Use pre-commit in ci to test flake8 & black

Add pre-commit setup

---

msgspec/_core.c
tests/test_common.py

Previously we added support for tagged unions by generating a lookup
table from tag -> struct type containing all struct types in the union.
However, if the same struct union type was used in multiple places (or
was passed in to `decode(..., type=some_union)` multiple times), the
lookup table would be regenerated each time. This is suboptimal for two
reasons:
- It's doing unnecessary work. While this work ideally would only be
done a fixed number of times on setup (e.g. while creating all `Decoder`
objects used), it's also not uncommon for users to call the top-level
decode functions, which would end up recreating the lookup table on
every call.
- It results in excessive memory usage. While the memory usage itself is
likely negligible compared to other parts of the application, it can …

Cache struct lookup tables

---

.pre-commit-config.yaml
docs/source/usage.rst
msgspec/_core.c
tests/test_json.py
tests/test_msgpack.py

Adds support for encoding/decoding `frozenset` instances.

Support frozenset objects

---

msgspec/_core.c

Rearranges the branches in ``mpack_encode`` to put the most likely types
first (str, int, ...). This is a micro-optimization, but is easy to do.
Experiments show up to 5% speedup for tiny messages.

Optimize branch ordering of mpack_encode

---

msgspec/_core.c
tests/test_json.py

Assorted JSON decoder optimizations. 5-10% perf speedups for str and int decoding.

Micro-optimize json decode

---

msgspec/_core.c

Instead of checking subtypes, we can check if the type of the type is
EnumMeta. This results in a 20% speedup in encoding IntEnum objects.

Faster enum checks

---

docs/source/structs.rst

fix tagged union example in docs

---

docs/source/changelog.rst

Updates changelog. Also adds github PR links for all changelog entries.

Release 0.7.0

---

benchmarks/bench_library_size.py
docs/source/benchmarks.rst
docs/source/index.rst

Adds a benchmark for installed library size, measuring the total amount
of disk space consumed for various comparable libraries.

Add benchmark for library size

---

docs/source/structs.rst

Clarify `__hash__` behavior when `frozen=True`

---

docs/source/usage.rst
msgspec/_core.c
tests/test_common.py
tests/test_json.py
tests/utils.py

Add TypedDict support

---

.codecov.yml
README.rst

- Add codecov badge to readme
- Adjust codecov settings (no comment, looser thresholds)

Codecov updates

---

.github/workflows/ci.yml
msgspec/_core.c
tests/test_struct.py

This:
- Fixes (hopefully) some python 3.11 bugs/incompatibilities
- Adds Python 3.11 prereleases to our test matrix (linux only)
Fixes #143

Python 3.11 support & testing

---

msgspec/_core.c

There were a few places where we were accidentally not using the
specialized API.

PyDict_Size -> PyDict_GET_SIZE

---

msgspec/_core.c
tests/test_struct.py

This fixes a segfault introduced in #146. This bug was never released.
- Before Python 3.11, calling `PyObject_GC_Del` worked the same as
`PyObject_Del`, where it was functionally equivalent to `free`, only
treating the argument as an opaque pointer.
- In Python 3.11, `PyObject_GC_Del` accesses the `ob_type` field to
determine the size of the GC header. This didn't play well with our
freelist implementation.
- To work around this, #146 moved to keeping the `ob_type` field on
objects in the freelist, only decref'ing their type when the memory is
used, or when it is cleared by `Struct_freelist_clear`.
- However, `Struct_freelist_clear` is called during a GC traversal. In
rare circumstances, an object stored in our freelist can contain the
only reference to a `StructMeta` type object. …

Fix rare segfault in StructMeta_dealloc

---

tests/test_cpylint.py

`git add` fail :facepalm:
See also #156.

Actually add the cpython linting tests

---

msgspec/_core.c
tests/test_json.py
tests/test_msgpack.py

This used to work, but lapsed. Looks like there never was a test that
hit this case :/.
Fixes #159.

Fix decoding Optional[custom type]

---

msgspec/_core.c

A good portion of int encoding time was spent in
`PyLong_AsLongLongAndOverflow`/`PyLong_AsUnsignedLongLong`, and
associated branching on overflow. By poking at the cpython internals we
can:
- Avoid the cost of a black-box function
- Optimize branching for our use case (extract into a uint64_t + sign,
erroring if the value doesn't fit in an `int64`/`uint64`).
- Avoid doing unnecessary work in the case of values > int64.
This optimization results in a 15-25% speedup in JSON integer encoding,
and a 25-35% speedup in msgpack integer encoding (for a large list of
integers).
Since the internal representation of integers in cpython hasn't changed
in years, and seems unlikely that it will change in the future, I don't
forsee this being a maintenance burden.

Optimize int encoding

---

docs/source/_static/custom.css
docs/source/conf.py
docs/source/index.rst
docs/source/usage.rst

Some CSS changes to improve (IMO) the legibility of the docs.

Improve docs styling

---

.pre-commit-config.yaml
docs/source/examples/asyncio-kv.rst
docs/source/examples/index.rst
examples/asyncio-kv/kv.py

Adds an example of using asyncio & msgspec to define a key-value store server and client.

Add Asyncio TCP KV server/client example

---

msgspec/_core.c
tests/test_json.py

Previously the JSON decoder would error if a `datetime` string was encountered with > microsecond resolution. Since Python datetimes (and many systems) only support microsecond resolution, this limitation was deemed fine until someone asked for support. That's now happened :).
We now support datetime strings with infinite precision, rounding to the nearest microsecond. This means that these timestamps won't roundtrip accurately through msgspec if parsed into python `datetime` objects, but there's not much we can do to work around that.
Fixes #200.

Support > microsecond resolution in JSON timestamps

---

README.rst
docs/source/index.rst
setup.py

- Fixup styling of readme
- A few prose edits

Small edits

---

msgspec/_core.c

This inlines and reorganizes code in the `json_encode` dispatch. The main benefits of this are:
- Move less common types into a separate function
- Inline the common type dispatch in collection types where the value is likely to be uniformly typed. This includes `list`, `set`, `dict`, and `tuple`, but excludes structured data types like `struct`/`dataclass`.
This results in a 12% perf improvement on common benchmark datasets.
I think this is due to a mix of improved locality and branch prediction. Inlining results in each collection type having its own copy of the common branches, which the branch predictor will track separately. This means that encoding a `dict[str, list[int]]` type will have `json_encode_dict` predicting to take the `list` branch and `json_encode_list` predicting to …

Inline common JSON encode dispatch

---

msgspec/_core.c

This selectively inlines and reorganizes code in the `mpack_encode` dispatch, following the same optimization already applied to the JSON encoder (#294).
On my machine this results in up to a 15% speedup in encoding speed.
Inlining is done selectively, only in collections where the value types are likely to be homogenous (resulting in better branch prediction). The increase in library size is tiny (136 bytes), and no regressions were found in our benchmark suite.

Inline common msgpack encode dispatch

---

docs/source/install.rst

Adds install docs on
- optional dependencies
- installing from github

Expand install docs

---

docs/source/changelog.rst
docs/source/converters.rst
docs/source/index.rst

- A few small docs edits
- Update changelog for 0.13.0 release

Release 0.13.0

---

msgspec/_core.c
tests/test_json.py

When we allowed decoding JSON from a `str` instead of a bytes-like type, we missed handling the case of decoding a `str` into a `Raw` type. This fixes that issue.
Fixes #317.

Fix bug preventing json decoding str -> Raw type

---

msgspec/_core.c
tests/test_struct.py

Previously we only allowed struct types to subclass from other struct types. We now structs to include any base class that:
- Doesn't have a metaclass (this is actually a CPython restriction, and has nothing to do with `msgspec`).
- Doesn't define `__init__` or `__new__`.
A main use case of this is "mixin" types that add a few additional methods, and may work on types other than structs (if they only work on structs, the mixin should really already be a `Struct` type anyway).
For mild efficiency reasons we recommend defining `__slots__ = ()` when possible on your mixin types to avoid allocating unnecessary space for a `__dict__`, but this isn't required.
Fixes #296.

Allow mixins in Struct types

---

docs/source/structs.rst

Add note about using functools.partial with default_factory

---

msgspec/__init__.py
msgspec/_core.c

No sense in duplicating these docstrings.

Share docstring between field & Field

---

msgspec/_core.c
tests/test_msgpack.py

This PR changes the msgpack decoder to avoid preallocating large arrays. This reduces the ability for malicious messages to allocate large amounts of memory with only a small payload.
We still preallocate small arrays (current threshold is 16 elements). This means that a crafted message of N bytes could result in at most `N * 184` bytes being allocated, with `N` being at most `sys.getrecursionlimit()`. Dropping to no preallocations would reduce this to `N * 56` bytes (~1/3 of the above usage), but comes with a ~20% performance decrease for small arrays. Given common CPython configurations, this means that a 3000 byte message could result in at most ~500 KiB being allocated, which is low enough to be acceptable.
With this change, all allocations in the decoder scale only with the size of …

Don't preallocate large arrays in msgpack decoder

---

msgspec/_json_schema.py
msgspec/inspect.py
tests/test_inspect.py
tests/test_schema.py

This adds support for generic structs to our introspection utilities (`msgspec.inspect`/`msgspec.json.schema`). This is a follow-up to #386.

Support Generic structs in `msgspec.inspect`/`msgspec.json.schema`

---

docs/source/supported-types.rst
msgspec/_core.c
msgspec/_utils.py
msgspec/inspect.py
tests/test_common.py
tests/test_inspect.py
tests/test_schema.py

Support generic `TypedDict` and `NamedTuple` types

---

msgspec/_core.c
tests/test_from_builtins.py

This adds support for passing generic mapping objects to `from_builtins`. These may be coerced to `dict`, `Struct`, `dataclass`, or `attrs` types.
Fixes #423.

Support mappings as inputs to `from_builtins`

---

msgspec/_core.c
tests/test_convert.py

This adds a new convert path from `decimal.Decimal` -> `float` types.

Support convert decimal -> float

---

.github/workflows/ci.yml
.isort.cfg
.pre-commit-config.yaml
pyproject.toml
setup.cfg

Migrate from `flake8` & `isort` to `ruff` and update pre-commit config
https://github.com/astral-sh/ruff

Migrate from `flake8` & `isort` to `ruff` and update pre-commit config

---

docs/source/usage.rst

Add missing comma to python code in usage docs section

---

.pre-commit-config.yaml
pyproject.toml
tests/test_inspect.py

https://astral.sh/blog/the-ruff-formatter

Use ruff format

---

msgspec/_core.c
tests/test_struct.py

Previously we prevented setting `gc=False` when inheriting from any non-Struct type. In reality this is safe to set when inheriting from any non-c-extension class lacking a `__dict__`.
Fixes #631.

Support inheriting from slots classes with gc=False

---

msgspec/__init__.py
msgspec/__init__.pyi
tests/basic_typing_examples.py
tests/test_convert.py

Remove deprecated `from_builtins`

---

docs/source/conf.py

https://www.sphinx-doc.org/en/master/usage/configuration.html#config-copyright

remove copyright year in docs
